"""create table test

Revision ID: 07642724ff8a
Revises: b4d21d784a09
Create Date: 2026-03-13 17:55:56.923188

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07642724ff8a'
down_revision = 'b4d21d784a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('classid', sa.INTEGER(), nullable=False),
    sa.Column('classdesc', sa.TEXT(), nullable=True),
    sa.Column('classvenue', sa.TEXT(), nullable=True),
    sa.Column('subjectcode', sa.TEXT(), nullable=True),
    sa.Column('classstarttime', sa.TEXT(), nullable=True),
    sa.Column('classendtime', sa.TEXT(), nullable=True),
    sa.Column('academicsession', sa.TEXT(), nullable=True),
    sa.Column('classtype', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('classid')
    )
    op.create_table('educator',
    sa.Column('educatorid', sa.TEXT(), nullable=False),
    sa.Column('educatorname', sa.TEXT(), nullable=True),
    sa.Column('educatoremail', sa.TEXT(), nullable=True),
    sa.Column('educatorpass', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('educatorid')
    )
    op.create_table('student',
    sa.Column('studentid', sa.TEXT(), nullable=False),
    sa.Column('studentname', sa.TEXT(), nullable=True),
    sa.Column('studentemail', sa.TEXT(), nullable=True),
    sa.Column('refembedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.PrimaryKeyConstraint('studentid')
    )
    op.create_table('attendance',
    sa.Column('studentid', sa.TEXT(), nullable=False),
    sa.Column('classid', sa.INTEGER(), nullable=False),
    sa.Column('weekheld', sa.INTEGER(), nullable=True),
    sa.Column('presentstate', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['classid'], ['class.classid'], ),
    sa.ForeignKeyConstraint(['studentid'], ['student.studentid'], ),
    sa.PrimaryKeyConstraint('studentid', 'classid', 'weekheld')
    )
    op.create_table('enrolment',
    sa.Column('studentid', sa.TEXT(), nullable=False),
    sa.Column('classid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['classid'], ['class.classid'], ),
    sa.ForeignKeyConstraint(['studentid'], ['student.studentid'], ),
    sa.PrimaryKeyConstraint('studentid', 'classid')
    )
    op.create_table('my_classes',
    sa.Column('educatorid', sa.TEXT(), nullable=False),
    sa.Column('classid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['classid'], ['class.classid'], ),
    sa.ForeignKeyConstraint(['educatorid'], ['educator.educatorid'], ),
    sa.PrimaryKeyConstraint('educatorid', 'classid')
    )
#     op.drop_table('users')
#     with op.batch_alter_table('tblvector', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.BIGINT(),
#                type_=sa.String(length=100),
#                existing_nullable=False)
#         batch_op.alter_column('embedding',
#                existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3),
#                type_=postgresql.ARRAY(sa.Float()),
#                nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('tblvector', schema=None) as batch_op:
#         batch_op.alter_column('embedding',
#                existing_type=postgresql.ARRAY(sa.Float()),
#                type_=pgvector.sqlalchemy.vector.VECTOR(dim=3),
#                nullable=True)
#         batch_op.alter_column('id',
#                existing_type=sa.String(length=100),
#                type_=sa.BIGINT(),
#                existing_nullable=False)

#     op.create_table('users',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
#     sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
#     )
    op.drop_table('my_classes')
    op.drop_table('enrolment')
    op.drop_table('attendance')
    op.drop_table('student')
    op.drop_table('educator')
    op.drop_table('class')
    # ### end Alembic commands ###
