"""Initial migration

Revision ID: b4d21d784a09
Revises: 
Create Date: 2026-03-11 21:25:45.637948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d21d784a09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('col1',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
        batch_op.alter_column('col2',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)

       # Removed any changes to tblVector
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tblvector', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.NullType(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=100),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('col2',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
        batch_op.alter_column('col1',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)

    # ### end Alembic commands ###
